version: '3'
services:
  node-app:
        container_name: "express-node-app-container"
      
        working_dir: /app/src
        build: .
        ports:
          - "4000:4000"
        volumes:
          - ./src:/app/src:ro